version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
